### ISSUE TITLE
restview as a service?

### ISSUE THREAD

**Issue by msabramo** [mgedmin/restview#27]
It would be cool if there were a website that offered restview so folks could easily validate their reST.

I wonder if python.org folks would give you a server to run it on?

I've used http://rst.ninjs.org/ on occasion, but it doesn't catch all of the problems that `restview` with `--pypi-strict` finds because the latter copies code from PyPI that is over and above what docutils enforces (which is awesome, by the way!).

**Comment by mgedmin** [comment]
It's an interesting idea.  I'm afraid I don't have the time or interest to pursue it, though.

There are also [security implications](https://bitbucket.org/pypa/pypi/issue/161/rest-formatting-fails-and-there-is-no-way#comment-12340944) which is why PyPI itself doesn't show the RST errors to the uploader.
